version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "golang-lambda"
s3_prefix = "golang-lambda"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
